In [1]:
import tensorflow as tf
a = tf.constant([1.0,2.0],name="a")
b = tf.constant([2.0,3.0],name="b")
result = a + b 
print (a.graph is tf.get_default_graph())

True


In [2]:
g1 = tf.Graph()
with g1.as_default():
    v = tf.get_variable("v",shape=[1],
                        initializer=tf.zeros_initializer(dtype=tf.float32))
    
g2 = tf.Graph()
with g2.as_default():
    v = tf.get_variable("v",shape=[1],
                        initializer=tf.ones_initializer(dtype=tf.float32))

with tf.Session(graph=g1) as sess:
    tf.global_variables_initializer().run()
    with tf.variable_scope("",reuse=True):
        print sess.run(tf.get_variable("v"))
        
with tf.Session(graph=g2) as sess:
    tf.global_variables_initializer().run()
    with tf.variable_scope("",reuse=True):
        print sess.run(tf.get_variable("v"))

[ 0.]
[ 1.]


In [3]:
import tensorflow as tf 
# a = tf.constant([1.0,2.0],name="a")
a = tf.constant([1,2],name="a",dtype=tf.float32)
b = tf.constant([2.0,3.0],name="b")
result = a + b
# result = tf.add(a,b,name="add")
# print result

In [4]:
with tf.Session() as sess:
    print result.eval()

[ 3.  5.]


In [7]:
sess = tf.InteractiveSession()
print result.eval()
sess.close()
config = tf.ConfigProto(allow_soft_placement=True,
                       log_device_placement=True)
sess1 = tf.InteractiveSession(config=config)
sess2 = tf.Session(config=config)

[ 3.  5.]


In [29]:
sess = tf.InteractiveSession()
print sess.run(tf.zeros([2,3],dtype=tf.int32))
print '==========='
print sess.run(tf.ones([2,3],dtype=tf.int32))
print '==========='
print sess.run(tf.fill([2,3],9))
print '==========='
print sess.run(tf.constant([1,2,3]))
weights = tf.Variable(tf.random_normal([2,3],stddev=2))
w2 = tf.Variable(weights.initialized_value())
w3 = tf.Variable(weights.initialized_value()*2.0)
print sess.run(w3.initialized_value())


[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]
[[9 9 9]
 [9 9 9]]
[1 2 3]
[[-1.19379067  3.65190196 -0.46347058]
 [ 3.46229315  3.35304666 -3.17724109]]


In [35]:
#前向传播
import tensorflow as tf 
w1 = tf.Variable(tf.random_normal([2,3],stddev=1,seed=1))
w2 = tf.Variable(tf.random_normal([3,1],stddev=1,seed=1))
x = tf.constant([[0.7,0.9]])
a = tf.matmul(x,w1)
y = tf.matmul(a,w2)
sess = tf.InteractiveSession()
sess.run(tf.global_variables_initializer())
print sess.run(y)

[[ 3.95757794]]


In [37]:
#前向传播
import tensorflow as tf 
w1 = tf.Variable(tf.random_normal([2,3],stddev=1,seed=1))
w2 = tf.Variable(tf.random_normal([3,1],stddev=1,seed=1))
x = tf.placeholder(dtype=tf.float32,shape=(3,2),name="input")
a = tf.matmul(x,w1)
y = tf.matmul(a,w2)
cross_entry = - tf.reduce_mean(y_*tf.log(tf.clip_by_value(y,le-10,1.0)))
learning_rate = 0.001
trian_step = tf.train.AdamOptimizer(learning_rate).minimize(cross_entry)
sess = tf.InteractiveSession()
sess.run(tf.global_variables_initializer())
print sess.run(y,feed_dict={x:[[0.7,0.9],[0.1,0.4],[0.5,0.8]]})

[[ 3.95757794]
 [ 1.15376544]
 [ 3.16749191]]
